from sqlalchemy import Column, String, Text, DateTime, UUID, Integer, JSON, Index
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, TSVECTOR, ARRAY
from sqlalchemy.sql import func
from .database import Base
import uuid
from pgvector.sqlalchemy import Vector

class Document(Base):
    __tablename__ = "documents"

    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(String, nullable=False, index=True)
    filename = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    sha256 = Column(String(64), nullable=False, unique=True)
    storage_key = Column(String, nullable=False)
    status = Column(String, nullable=False, default='queued', index=True)
    error_detail = Column(Text, nullable=True)
    metadata = Column(JSON, nullable=False, default={})
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index('documents_tenant_status', 'tenant_id', 'status'),
    )

class Chunk(Base):
    __tablename__ = "chunks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    document_id = Column(PG_UUID(as_uuid=True), nullable=False, index=True)
    chunk_idx = Column(Integer, nullable=False)
    page = Column(Integer, nullable=True)
    content = Column(Text, nullable=False)
    chunker_version = Column(String, nullable=False)
    embedding_model = Column(String, nullable=True)
    embedding = Column(Vector(768), nullable=True)  # Dimension will be set based on the embedding model
    tsv = Column(TSVECTOR, nullable=False)  # This is generated by the database

    __table_args__ = (
        Index('chunks_document_id', 'document_id'),
        Index('chunks_chunk_idx', 'document_id', 'chunk_idx', unique=True),
    )