from sqlalchemy import Column, String, Text, DateTime, UUID, Integer, JSON, Index
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, TSVECTOR, ARRAY
from sqlalchemy.sql import func
from .database import Base
import uuid
from pgvector.sqlalchemy import Vector

class Document(Base):
    __tablename__ = "documents"

    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(String, nullable=False, index=True)
    filename = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    sha256 = Column(String(64), nullable=False, unique=True)
    storage_key = Column(String, nullable=False)
    status = Column(String, nullable=False, default='queued', index=True)
    error_detail = Column(Text, nullable=True)
    metadata = Column(JSON, nullable=False, default={})
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index('documents_tenant_status', 'tenant_id', 'status'),
    )

class Chunk(Base):
    __tablename__ = "chunks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    document_id = Column(PG_UUID(as_uuid=True), nullable=False, index=True)
    chunk_idx = Column(Integer, nullable=False)
    page = Column(Integer, nullable=True)
    content = Column(Text, nullable=False)
    chunker_version = Column(String, nullable=False)
    embedding_model = Column(String, nullable=True)
    # We'll use the vector type from pgvector, but note: we are using SQLAlchemy and the vector type is not natively supported.
    # We'll store the embedding as a LargeBinary (or we can use an array of floats) but for simplicity, we'll use LargeBinary and handle the conversion in the application.
    # However, note that the document specifies a vector column. We'll use the pgvector extension and the vector type via SQLAlchemy.
    # Since we are using PostgreSQL, we can use the `vector` type from the `pgvector` package, but we need to install it and use the correct dialect.
    # For now, we'll leave it as a placeholder and note that we need to use the pgvector type.
    # We'll change this to use the vector type when we have the pgvector extension installed and the dialect set up.
    # Alternatively, we can store the embedding as an array of floats, but the document specifies a vector type.
    # Let's use the `Vector` type from `pgvector` if available, otherwise we'll use a placeholder.
    # We'll import it conditionally or note that we need to adjust.
    # For the sake of this example, we'll use a LargeBinary and note that we need to change it to the vector type when using pgvector.
    embedding = Column(Vector(768), nullable=True)  # Dimension will be set based on the embedding model
    tsv = Column(TSVECTOR, nullable=False)  # This is generated by the database

    __table_args__ = (
        Index('chunks_document_id', 'document_id'),
        Index('chunks_chunk_idx', 'document_id', 'chunk_idx', unique=True),
    )